# ==========================================
# STAGE 1: Builder
# ==========================================
FROM ubuntu:22.04 AS  machinepay_deps

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install Build Dependencies
# Added python3 which is often required for Boost build scripts
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bison \
        flex \
        ca-certificates \
        curl \
        git \
        pkg-config \
        unzip \
        zip \
        tar \
        build-essential \
        python3 \
        linux-libc-dev \
        autoconf \
        libtool \
        automake \
        autoconf-archive \
        ca-certificates \
        libstdc++6 \
        runit \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV VCPKG_ROOT=/app/vcpkg \
    VCPKG_DISABLE_METRICS=1


RUN git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT && \
    $VCPKG_ROOT/bootstrap-vcpkg.sh


COPY vcpkg.json .

RUN $VCPKG_ROOT/vcpkg install --triplet x64-linux



