# ==========================================
# STAGE 1: Builder
# ==========================================
FROM ubuntu:22.04 AS  machinepal_deps

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install Build Dependencies
# Added python3 which is often required for Boost build scripts
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bison \
        flex \
        ca-certificates \
        curl \
        git \
        pkg-config \
        unzip \
        zip \
        tar \
        build-essential \
        python3 \
        linux-libc-dev \
        autoconf \
        libtool \
        automake \
        autoconf-archive \
        ca-certificates \
        libstdc++6 \
        runit \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


RUN git clone https://github.com/skalenetwork/machinepal --recursive

ENV VCPKG_ROOT=/app/vcpkg \
    VCPKG_DISABLE_METRICS=1


RUN git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT && \
    $VCPKG_ROOT/bootstrap-vcpkg.sh


COPY vcpkg.json .
COPY external external

# --- FIX: Install Build Tools (CMake & Ninja) ---
# If your deps image doesn't include these, you must install them here.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y ca-certificates gpg wget \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update \
    && apt-get install -y cmake ccache

# Verify version
RUN cmake --version

RUN $VCPKG_ROOT/vcpkg install --triplet x64-linux






