# ==========================================
# STAGE 1: Builder
# ==========================================
FROM ubuntu:22.04

# Copy both the package list and the script to /tmp
COPY packages.txt install_packages.sh /tmp/

# Make the script executable and run it
# We use bash explicitly to run it, ensuring compatibility
RUN cd /tmp && ./install_packages.sh

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN git clone https://github.com/skalenetwork/machinepal --recursive --depth 1 --shallow-submodules
ADD https://www.google.com /tmp/bust-cache
RUN cd machinepal && git pull && git submodule update --recursive


# --- SIMPLIFICATION HERE ---
# Setting WORKDIR here means all future commands happen inside this folder
WORKDIR /app/machinepal

# 4. Setup VCPKG
ENV VCPKG_ROOT=/app/machinepal/external/vcpkg \
    VCPKG_DISABLE_METRICS=1 \
    VCPKG_FORCE_SYSTEM_BINARIES=1
    # ^ FORCE_SYSTEM_BINARIES prevents vcpkg from downloading its own cmake/ninja tools, saving time.

RUN cd docker && ./vcpkg_packages_install.sh

# 6. Configure
# Your project is RelWithDebInfo, which links to the Release deps built above.
RUN cmake -S . -B build \
      -G Ninja \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
      -DVCPKG_TARGET_TRIPLET=x64-linux


# 7. Build (No 'cd' needed)
RUN cmake --build build && find build -name "*.o" -type f -delete \
    && rm -rf $VCPKG_ROOT/buildtrees \
    && rm -rf $VCPKG_ROOT/downloads \
    && rm -rf build/*/

