# ==========================================
# STAGE 1: Builder
# ==========================================
FROM ubuntu:22.04 AS  machinepal_deps

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install Build Dependencies
# Added python3 which is often required for Boost build scripts
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bison \
        flex \
        ca-certificates \
        curl \
        git \
        pkg-config \
        unzip \
        zip \
        tar \
        build-essential \
        python3 \
        linux-libc-dev \
        autoconf \
        libtool \
        automake \
        autoconf-archive \
        ca-certificates \
        libstdc++6 \
        runit \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


RUN git clone https://github.com/skalenetwork/machinepal --recursive

ENV VCPKG_ROOT=/app/machinepal/external/vcpkg \
    VCPKG_DISABLE_METRICS=1


RUN $VCPKG_ROOT/bootstrap-vcpkg.sh

# --- FIX: Install Build Tools (CMake & Ninja) ---
# If your deps image doesn't include these, you must install them here.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y ca-certificates gpg wget \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update \
    && apt-get install -y cmake ccache

# Verify version
RUN cmake --version

# vcpkg.json (manifest) is in /app/machinepal
RUN cd /app/machinepal && $VCPKG_ROOT/vcpkg install --triplet x64-linux


# 3. Configure (CMake)`
# Now 'cmake' will be found in /usr/bin/cmake
RUN cd /app/machinepal && cmake -S . -B build \
      -G Ninja \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
      -DVCPKG_TARGET_TRIPLET=x64-linux

# 4. Build
RUN cd /app/machinepal && cmake --build build
