# ==========================================
# STAGE 1: Builder
# ==========================================
FROM ubuntu:22.04 AS  machinepal_deps

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install Build Dependencies
# Added python3 which is often required for Boost build scripts
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bison \
        flex \
        ca-certificates \
        curl \
        git \
        pkg-config \
        unzip \
        zip \
        tar \
        build-essential \
        python3 \
        linux-libc-dev \
        autoconf \

        libtool \
        automake \
        autoconf-archive \
        ca-certificates \
        libstdc++6 \
        runit \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/skalenetwork/machinepal --recursive

# --- SIMPLIFICATION HERE ---
# Setting WORKDIR here means all future commands happen inside this folder
WORKDIR /app/machinepal

# 4. Setup VCPKG
ENV VCPKG_ROOT=/app/machinepal/external/vcpkg \
    VCPKG_DISABLE_METRICS=1

RUN $VCPKG_ROOT/bootstrap-vcpkg.sh

# 5. Install Dependencies (No 'cd' needed)
RUN $VCPKG_ROOT/vcpkg install --triplet x64-linux

# 6. Configure (No 'cd' needed)
RUN cmake -S . -B build \
      -G Ninja \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
      -DVCPKG_TARGET_TRIPLET=x64-linux

# 7. Build (No 'cd' needed)
RUN cmake --build build

# 8. Clean up (No 'cd' needed - FIXED YOUR ERROR)
# Since we are in /app/machinepal, 'find build' now correctly sees the build folder
RUN find build -name "*.o" -type f -delete \
    && rm -rf $VCPKG_ROOT/buildtrees \
    && rm -rf $VCPKG_ROOT/downloads

